import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook Next</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/*Header*/}
      {/*Sidebar*/}
      {/*NewsFeed*/}
      {/*ChatHeads*/}
    </div>
  );
}
